// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhwhmkhtcvkislfupkqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1od2hta2h0Y3ZraXNsZnVwa3F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNDAyNDIsImV4cCI6MjA2MDcxNjI0Mn0.JdNwCuySDw6IpwBuW_hW-CRArJh_HHwVgl9yG7zuq9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);